# プロジェクト設定
spring.application.name=${SPRING_APPLICATION_NAME}
spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE}

# ログイン設定
spring.security.user.name=${SPRING_SECURITY_USER_NAME:users}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:passw}

# データベース設定
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSEORD}
# @Entity を使ってクラスを定義すると、Spring Bootがデータベースに対応するテーブルを自動生成
# updateの他に none、validate、create、create-dropなどがある
#update は開発向け、本番は validate/none ＋ Flyway/Liquibase を推奨
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL-AUTO}
# Hibernate（JPA）によるテーブル自動作成の後にdata.sql（初期データ投入）を実行（Spring Boot 2.5以降で必要な設定）
spring.jpa.defer-datasource-initialization=${SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION}

# Stripe（クレジット決済機能）　※ポートフォリオサイトにつき無効化している
stripe.api-key=${STRIPE_API-KEY}
stripe.success-url=${STRIPE_SUCCESS-URL}
stripe.cancel-url=${STRIPE_CANCEL-URL}
stripe.webhook-secret=${STRIPE_WEBHOOK-SECRET}

# メール認証機能　※ポートフォリオサイトにつき無効化している
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}